USGS-CIDA/gcmrc-ui-parent

- gcmrc-ui/src/main/webapp/app/gcmrc.jsp
- gcmrc-ui/src/main/webapp/app/mapping.js
- gcmrc-ui/src/main/webapp/app/networkdata.js
- gcmrc-ui/src/main/webapp/app/reachdata.js
- gcmrc-ui/src/main/webapp/pages/networkreachview/page.js
Dave - this seems to be working but please review and let me know if I've missed anything.
> gcmon-234 and gcmon-235; initial review

- gcmrc-ui/src/main/webapp/pages/index/page.js
@davidmsibley - this seems to work but please take a quick look when you get a chance in case there is a better approach.  thanks.
> gcmon-298; hide link to reaches page when there are none

- gcmrc-services/src/main/java/gov/usgs/cida/gcmrcservices/jsl/data/ParameterSpec.java
- gcmrc-services/src/main/java/gov/usgs/cida/gcmrcservices/jsl/station/StationParamSpec.java
- gcmrc-services/src/main/java/gov/usgs/cida/gcmrcservices/jsl/station/StationSiteSpec.java
- gcmrc-services/src/main/resources/gov/usgs/cida/gcmrcservices/mb/mappers/ReachDetailMapper.xml
- gcmrc-services/src/main/resources/gov/usgs/cida/gcmrcservices/mb/mappers/ReachMapper.xml
@kmschoep-usgs care to check this out?
> Attempt to include SQL hint for old optimizer

- gcmrc-ui/src/main/webapp/app/gcmrc.jsp
- gcmrc-ui/src/main/webapp/app/networkdata.js
- gcmrc-ui/src/main/webapp/index.jsp
- gcmrc-ui/src/main/webapp/pages/index/onReady.js
- gcmrc-ui/src/main/webapp/pages/index/page.js
- gcmrc-ui/src/main/webapp/pages/networkreachview/page.css
> Adding link to research river trip data

- gcmrc-services/src/main/java/gov/usgs/cida/gcmrcservices/column/ColumnMetadata.java
- gcmrc-services/src/main/java/gov/usgs/cida/gcmrcservices/column/ColumnResolver.java
- gcmrc-services/src/main/java/gov/usgs/cida/gcmrcservices/jsl/data/DischargeErrorSpec.java
- gcmrc-services/src/main/java/gov/usgs/cida/gcmrcservices/jsl/data/DownloadService.java
> Added discharge error to services. Uses hardcoded column name to request

- gcmrc-services/src/main/java/gov/usgs/cida/gcmrcservices/column/ColumnResolver.java
- gcmrc-services/src/main/java/gov/usgs/cida/gcmrcservices/jsl/data/DischargeErrorSpec.java
- gcmrc-services/src/main/java/gov/usgs/cida/gcmrcservices/jsl/param/ParamService.java
- gcmrc-services/src/main/java/gov/usgs/cida/gcmrcservices/jsl/station/StationDischargeErrorSpec.java
- gcmrc-ui/src/main/webapp/pages/stationview/page.js
- gcmrc-ui/src/main/webapp/stationview.jsp
> Added param description service for discharge measurements/error and now

- gcmrc-ui/src/main/webapp/pages/stationview/page.js
adding physical description to measurements, so physical measurements instead of just measurements
> updating label for sidebar on discharge physical measurements

- gcmrc-services/src/main/java/gov/usgs/cida/gcmrcservices/mb/endpoint/DurationCurveEndpoint.java
- gcmrc-services/src/main/java/gov/usgs/cida/gcmrcservices/mb/model/DurationCurve.java
- gcmrc-services/src/main/java/gov/usgs/cida/gcmrcservices/mb/model/DurationCurvePoint.java
- gcmrc-ui/src/main/webapp/app/graphing/graphing.js
- gcmrc-ui/src/main/webapp/pages/stationview/onReady.js
- gcmrc-ui/src/main/webapp/pages/stationview/page.css
- gcmrc-ui/src/main/webapp/pages/stationview/page.js
- gcmrc-ui/src/main/webapp/stationview.jsp
UI: Added duration curve interface.
Webservices: Updated DurationCurve services to allow multiple for groupIds and both binTypes in a single request.
> GCMON-370: Update UI to include duration curve plot interface

- gcmrc-ui/src/main/webapp/pages/reachview/page.js
i'm guessing this was a find/replace mistake, changing back as it's preventing the reaches from drawing correctly
> removing something that shouldn't have changed from reachviews

- gcmrc-ui/src/main/webapp/app/graphing/graphing.js
added to the blacklist
group_id 3, 4, 58, 61, and 115
> removing any cumulative timeseries from showing duration curve toggle

- gcmrc-ui/src/main/webapp/pages/stationview/page.js
> Upping binCount to 2000

- gcmrc-ui/src/main/webapp/app/graphing/MatrixWorker.js
- gcmrc-ui/src/test/javascript/MatrixBuildResources.js
- gcmrc-ui/src/test/javascript/MatrixBuildSpec.js
Fix for jasmine tests that were broken because of changes to bedload calculations.
> GCMRC-560 Fix broken tests

- gcmrc-ui/src/main/webapp/app/orgs.js
So the logos and credits were not appearing
> GCMON-602: forgot new orgs in orgs.js

- gcmrc-ui/src/main/webapp/app/networkdata.js
- gcmrc-ui/src/main/webapp/index.jsp
- re-arrange order of networks
- re-arrange location of Army Corps of Engineers on cooperator list
> GCMON-602: feedback from DT adjusting CHIP network

- gcmrc-ui/src/main/webapp/app/networkdata.js
- gcmrc-ui/src/main/webapp/pages/networkreachview/page.js
so that it includes the uintah basin reach
> Shift dinosaur network reach overview map

- gcmrc-services/src/main/java/gov/usgs/cida/gcmrcservices/mb/dao/DurationCurveDAO.java
- gcmrc-services/src/main/java/gov/usgs/cida/gcmrcservices/mb/model/DurationCurve.java
- gcmrc-services/src/main/java/gov/usgs/cida/gcmrcservices/mb/model/DurationCurveConsecutiveGapMinutes.java
- gcmrc-services/src/main/java/gov/usgs/cida/gcmrcservices/mb/service/DurationCurveService.java
- gcmrc-services/src/main/resources/gov/usgs/cida/gcmrcservices/mb/mappers/DurationCurveMapper.xml
- gcmrc-services/src/main/resources/mybatis-config.xml
- gcmrc-ui/src/main/webapp/app/graphing/graphing.js
@zmoore-usgs Going to merge this to get DT's eyes on it, but would like a review anyway.
> Gcmon 482 large gaps

- gcmrc-ui/src/main/webapp/app/graphing/graphing.js
> GCMON-482: Move data gap message to below the graph.

- pom.xml
> version 3.2.0 makes bad things show up in META-INF and I don't know why

- gcmrc-ui/src/main/webapp/app/graphing/graphing.js
otherwise erroneously adds another preceding 0
> Gcmon 701: make sure comparing string to string

- gcmrc-ui/src/main/webapp/template/custom.css
Basically needed to tell the HTML to be the min-height of the entire screen to allow other divs to be able to be adaptable sizes.  Should be the almost correct solution we need.
> Footer sticking to the bottom of pages

- gcmrc-ui/src/main/webapp/template/custom.css
Reverts USGS-CIDA/gcmrc-ui-parent#152
Will restage these changes on a new branch
> Revert "Footer sticking to the bottom of pages"

- gcmrc-services/src/main/resources/gov/usgs/cida/gcmrcservices/mb/mappers/LookupMapper.xml
- gcmrc-services/src/main/resources/gov/usgs/cida/gcmrcservices/mb/mappers/ReachMapper.xml
- gcmrc-services/src/main/resources/gov/usgs/cida/gcmrcservices/mb/mappers/StationMapper.xml
handled as Strings in the resulting json.
> define a javaType in the mybatis mappers so that number columns are

- gcmrc-services/src/main/java/gov/usgs/cida/gcmrcservices/mb/service/BedSedimentDownloadService.java
Noticed this while converting from Oracle --> Postgres. Fix needed in both branches. The Postgres fix will be bundled with my PR to the Postgres branch doing the conversion. This is the Oracle fix.
> [Oracle] Fixed NPE for BedSed Downloads.

- gcmrc-services/src/main/resources/gov/usgs/cida/gcmrcservices/mb/mappers/StationMapper.xml
- gcmrc-ui/src/main/webapp/pages/stationview/page.js
> Show the new Total Suspended Sediment parameter, both calculated and

- gcmrc-services/src/main/resources/gov/usgs/cida/gcmrcservices/mb/mappers/DurationCurveMapper.xml
> convert the jdbcType enum to uppercase.  Because it matters for some

- gcmrc-services/src/main/java/gov/usgs/cida/gcmrcservices/jsl/data/BedSedimentSpec.java
- gcmrc-services/src/main/java/gov/usgs/cida/gcmrcservices/jsl/data/DischargeErrorSpec.java
- gcmrc-services/src/main/java/gov/usgs/cida/gcmrcservices/jsl/data/ParameterSpec.java
- gcmrc-services/src/main/java/gov/usgs/cida/gcmrcservices/jsl/data/QWDataSpec.java
- gcmrc-services/src/main/resources/gov/usgs/cida/gcmrcservices/mb/mappers/BedSedimentDownloadMapper.xml
- gcmrc-services/src/main/resources/gov/usgs/cida/gcmrcservices/mb/mappers/QWDownloadMapper.xml
> change to_date() to to_timestamp() to get entire time portion accounted

- gcmrc-ui/pom.xml
- gcmrc-ui/src/main/webapp/index.jsp
- gcmrc-ui/src/main/webapp/networkreachview.jsp
- gcmrc-ui/src/main/webapp/reachview.jsp
- gcmrc-ui/src/main/webapp/stationview.jsp
- pom.xml
Remove dependency on CIDA Libs Opernlayers Decluster, remove stations from map on reach views
> Remove dependency, fix maps

- gcmrc-ui/src/main/java/gov/usgs/cida/gcmrc/util/PropertiesLoader.java
- gcmrc-ui/src/main/webapp/app/gcmrc.jsp
- gcmrc-ui/src/main/webapp/index.jsp
- gcmrc-ui/src/main/webapp/networkreachview.jsp
- gcmrc-ui/src/main/webapp/networkstationview.jsp
- gcmrc-ui/src/main/webapp/reachview.jsp
- gcmrc-ui/src/main/webapp/stationview.jsp
- pom.xml
be done when the webjars conversion is ported as well.
> Port DROP removal changes to Postgres branch.  Further work will need to

- gcmrc-ui/src/main/webapp/app/graphing/package.jsp
- gcmrc-ui/src/main/webapp/app/libs.jsp
- gcmrc-ui/src/main/webapp/index.jsp
- gcmrc-ui/src/main/webapp/js/angular-sortable/package.jsp
- gcmrc-ui/src/main/webapp/js/bootstrap-datepicker/package.jsp
- gcmrc-ui/src/main/webapp/js/proj4js/package.jsp
- gcmrc-ui/src/main/webapp/networkreachview.jsp
- gcmrc-ui/src/main/webapp/networkstationview.jsp
- gcmrc-ui/src/main/webapp/pages/page.jsp
- gcmrc-ui/src/main/webapp/reachview.jsp
- gcmrc-ui/src/main/webapp/stationview.jsp
- gcmrc-ui/src/main/webapp/template/GCMRCHead.jsp
- gcmrc-ui/src/main/webapp/template/GCMRCHeader.jsp
Switch to using the original method of figuring out relative paths in order to deal with relative paths
> Fix for relative paths issue

- gcmrc-services/src/main/resources/gov/usgs/cida/gcmrcservices/mb/mappers/StationMapper.xml
> remove "Cross-section Total Sediment Concentration" from station param

- gcmrc-services/src/main/resources/gov/usgs/cida/gcmrcservices/mb/mappers/StationMapper.xml
parameter list for all stations
> remove remove "Cross-section Total Sediment Concentration" from
